### ISSUE TITLE
Single type search pages (`search/<image|audio>`) should not use the store

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1010]
## Problem

Currently the image and audio search result pages get the `searchTerm` (`store.search.state.query.q`) as a prop, but they don't use it when setting the page title. Instead, they are calling the store again, and getting the value from the store.

## Description

We should replace the store access with props:
https://github.com/WordPress/openverse-frontend/blob/3ab03476a378768d329e3a21ec0f3a402bb4b560/src/pages/search/audio.vue#L49-L54
```
  setup(props) {
    const { i18n } = useContext()
    useMeta({ title: `${props.searchTerm} - Openverse` })
```

## Alternatives

We could remove all props, and just use the store in these pages. This would make the component more difficult to test.

## Additional context

It would be nice to somehow document which components are 'presentational', i.e. do not use the store values, only using the `props` passed from the parent component. Also, having the props definition in a separate file hides what props the component has, which might cause repeated access to the same piece of data.

## Implementation

- [x] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
> It would be nice to somehow document which components are 'presentational', i.e. do not use the store values, only using the props passed from the parent component

In the past I've used the Container suffix for the component that connects something to the store.

I think that's less useful for our application though.. those types of approaches never really worked to organize the code that well I thought, nothing was ever _easier_ to test, especially not in integration, sub-components that rendered the `Container` of something still invoked the store.

From a testing perspective it made more sense to make sure we had easy to use and maintainable mock stores that "just worked" including fixtures for filling the stores with API data (we can hopefully rely on Talkback tapes for this). Ideally the stores can be easily rigged to work in Storybook even. The global audio player and audio tracks for example could probably benefit from using a pinia store instead of a global ref (it'd be nice to replace all our global refs with pinia stores actually, considering our global refs are only _technically_ safe and we can't use `useState` from Nuxt 3 yet).

**Comment by sarayourfriend** [comment]
> Also, having the props definition in a separate file hides what props the component has, which might cause repeated access to the same piece of data.

I agree with this. I think I introduced the separated props object pattern and I regret it. However, in Vue 2 there's not really a great way to solve this problem, but I think potentially using the `extends` property could be one when there are actually shared props between components (like these). It should also work with TypeScript and Vue in Nuxt bridge when we get there.

```
// SearchPageProps.vue
export default defineComponent({
  props: {
    // ... search page props
  }
})

// AudioSearchPage.vue
import SearchPageProps from './SearchPageProps.vue'

export default defineComponent({
  extends: SearchPageProps,
  setup(props) {
    // etc...
  }
})
```

It still displaces the props, but allows for easily sharing them between components that have similar/exactly the same APIs and is more "Vue-y" I think (maybe). Generally I'd like to avoid a situation where we're having to copy-paste props between components with similar APIs, even when their shared behavior is encapsulated in a composable.

FWIW Vue 3 solves this as you can use the `defineProps` macro with a TypeScript definition, so prop sharing becomes as easy as this:

```vue
<script setup lang="ts">
import type { ComposableProps } from './use-some-shared-functionality'

interface Props extends ComposableProps {
  // .. my own props
}

const props = defineProps<Props>()
</script>
```

Until we can do that I'm not sure how best to fix the shared props problem.
