### ISSUE TITLE
Audit tree-shaking and dead-code removal when using environment flags from `node_env.ts`

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#1030]
## Problem

Verify that dead-code elimination works when `isDev`, `isTest` and `isProd` are used from `node_env.ts` instead of inline comparisons against `process.env.NODE_ENV`.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
Dead code elimination works fine currently, however we're not using to the fullest extent. For example, with the `console` module, we'd need to use a babel plugin to automatically wrap usages of those functions in `if (!isProd)` so the strings get removed.

We could just use the WordPress babel plugin for this instead of re-inventing the wheel: https://github.com/WordPress/gutenberg/blob/trunk/packages/warning/babel-plugin.js

**Comment by sarayourfriend** [comment]
Replaced by https://github.com/WordPress/openverse-frontend/issues/1146
