### ISSUE TITLE
Convert media results from an object to an array

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#1055]
## Problem

In the media store, the media results used to be stored in an array. Then, to simplify finding an item by ID, we converted it to an object with media ids as keys, and media details object as values. However, because we need arrays in most other places, we are constantly converting the object into array.

## Description

Media store items should be an array of `MediaDetail` objects.
We get the items as an array, and then have a process of converting them into an object. 
Here are places where we convert the object back into an array:

https://github.com/WordPress/openverse-frontend/blob/29bf0a0075548014a3d1280f0b56ae1f7e5f0b77/src/store/media.js#L166

https://github.com/WordPress/openverse-frontend/blob/29bf0a0075548014a3d1280f0b56ae1f7e5f0b77/src/pages/search/image.vue#L23

https://github.com/WordPress/openverse-frontend/blob/a2e7333e849b60c20f6cc55ea8fc914860c1490b/src/pages/search/audio.vue#L60

## Additional context
This would be nice to do before converting the `media` store to Pinia.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
Can we use store getters to obtain the results as an object or as an array depending on the needs?

**Comment by obulat** [comment]
Yes, we can, @dhruvkb ! In fact, I prefer to have a single source of truth in the store state, and convert it into any data structure that we need in the UI using getters.

**Comment by dhruvkb** [comment]
Makes sense. If that's the case, it'll be better to have the results be a dictionary then? Building a dictionary from an array in a getter is much more expensive that calling `Object.values(...)`.

**Comment by sarayourfriend** [comment]
I think the issue with using `Object.values` is that we'd be relying on insertion order (if we're lucky, [sometimes insertion order is _not_ the determining factor for Object key iteration order](https://stackoverflow.com/a/5525820)) to maintain the ordered results (which are presumably ordered significantly rather than randomly by the API).

Why not maintain both? When results are retrieved, use `Object.assign({}, existingResults, Object.fromEntries(results.map(r => [r.identifier, r])))` to build the new object mapping. Then we amortize the cost of building the object by doing it very rarely compared to how often results are accessed.

**Comment by obulat** [comment]
I'm closing this issue because currently the API can give duplicate results, and that makes using an Array (without de-duplicating it) impractical.
