### ISSUE TITLE
Warnings in dev command: `WARN  Cannot stringify a function bound`

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1237]
## Description

Run `pnpm dev` and observe multiple instances of the error `WARN  Cannot stringify a function bound`.

I would _suspect_ that this is a matter of a server-rendered setup function that returns a function which is stringified.

**Comment by sarayourfriend** [comment]
This is related to `@nuxt/devalue` which marshals state to and from the serialized version used for hydrating the client. Whomever looks into this might want to throw some debugging statements in devalue to see if they can tell _which_ function it is complaining about... It'd be nice if it would just call `toString` on the function so you could at least see the implementation and know where to debug in your app :shrug:

**Comment by sarayourfriend** [comment]
Appears this could be related to the media store to Pinia changes, I think that's when about I noticed this started to happen.

https://github.com/nuxt-community/composition-api/issues/386

The `search.vue` component uses both `fetch` and `setup`. Apparently this warning is unavoidable. Should we just ignore it? It's pretty annoying.

Alternatively, we can convert `search.vue` to not use `setup` anymore OR use `useFetch` from `@nuxtjs/composition-api` instead of `fetch` (which will be deprecated, but either way we'll need to re-write this component when upgrading to Bridge/Nuxt 3 it seems).

**Comment by sarayourfriend** [comment]
Assigning medium priority because this is pretty annoying for DX currently.

**Comment by obulat** [comment]
I think #1260 solves this issue. At least I couldn't see any warnings when I tried searching, viewing single media items and loading more items.

**Comment by sarayourfriend** [comment]
@obulat looks to me like it is fixed on that branch as well! Yay! :rocket:
