### ISSUE TITLE
Freesound download buttons link incorrectly

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1250]
## Description

Freesound download results do not work. We should fix this in the catalog, but also add a special exception in the frontend ASAP to link off the Freesound download buttons to the freesound page for the track itself.

## Reproduction

1. Visit any Freesound result: https://wordpress.org/openverse/audio/9af3243a-e4d4-4254-95d9-a3d53a0158c3
2. Click the download button
3. Observe the result is the failed API credential page: https://freesound.org/apiv2/sounds/20015/download/

## Environment

 - Device: 
 - OS: 
 - Browser: 
 - Version: 
 - Other info: 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
We can forward port the solution from https://github.com/WordPress/openverse/issues/1676 in the meantime until the catalog data is fixed.

**Comment by zackkrida** [comment]
I think my preference would be to link to the single result Freesound page and let users login or use the download button. It adds a step but I think it's clearer to users than landing directly on a login page.

**Comment by sarayourfriend** [comment]
@zackkrida should we just remove individual format downloads from the audio result page then and always link to the foreign landing url?

**Comment by sarayourfriend** [comment]
@WordPress/openverse How do people feel about temporarily switching _all_ audio download links to just be a single link to the foreign landing URL altogether? Just until we've figured out the exact right way to manage downloadable files and all their metadata that we'd like to show for them.

**Comment by panchovm** [comment]
I am completely fine with that. And also considering switching permanently to open-site only instead of downloading content.

**Comment by imouse1** [comment]
I am new to interfacing with GitHub or, really, knowing anything about it.  But in 29 of the last 30 files I tried to download, I still go the original error.  I tried it on 4 different devices, including a laptop, and different connections--LAN, Wi-Fi, Hotspot, Mobile Data.  I don't know how to fix it on my end because I don't think I fully understand the other part of why it is occuring.

![image](https://user-images.githubusercontent.com/98972059/167978842-05266a1c-811e-4d4e-ba4f-94ed8ad9b979.png)

https://search.openverse.engineering/audio/f06095bd-d6d1-4b65-a141-3b3fe0013c85

Also, not sure if it's part of the same thing, related, or different, but almost nothing labeled mp3 is an actual mp3.  I don't know if it's maybe because it is trying to generate labels or something to do with it supposing to be an mp3 but then being in a different format.

**Comment by zackkrida** [comment]
Hi @imouse1, if you go to the url you provided now:

https://search.openverse.engineering/audio/f06095bd-d6d1-4b65-a141-3b3fe0013c85

is the behavior different? it should now link to the single result on Freesound where you can use their _download_ button.

**Comment by imouse1** [comment]
Zach, 

Yes!  It even showed a button to login.  And after thar I was able to and download it.

Thank you so much!  Is there a formula for how I should change the URL?

Much appreciated!
Mouse

PS--I tried attaching a video to show you but IDK if it did.  Sorry if it shows up twice!

**Comment by zackkrida** [comment]
You're welcome. We pushed an update to Openverse today, so this should continue to work for any other Freesound audio files you visit. 😄 Thanks for reporting this bug and using Openverse!
