### ISSUE TITLE
Consider removing thumbnails from the talkback proxy

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#1277]
## Assigned reviewers

- [ ] @obulat 
- [ ] @sarayourfriend 

## Description

There are _a lot_ of tapes for audio and image thumbnails. Saving them seems to add considerable time to the tape updating process. These responses are largely inconsequential—we don't read their headers or any specific data anywhere, for example, we only display the images. What if we used a single mocked response with a default image to replace _all_ thumbnails, using `route.fulfill`, perhaps in a [global setup](https://playwright.dev/docs/api/class-testconfig#test-config-global-setup) script?

**Comment by zackkrida** [comment]
Eh, they don't actually take very long, but do add a lot of clutter and diffing nonetheless.

**Comment by sarayourfriend** [comment]
It may not be possible to use playwright's route mocking for the thumbnails because they're only mocked on the client, SSR requests wouldn't get the same mocking treatment.

I don't think we can use a single thumbnail for every one due to how talkback matches tapes, unless we found some way to automatically symlink all thumbnail tapes to a single response in a post-update-tapes script or something.

**Comment by sarayourfriend** [comment]
> Eh, they don't actually take very long, but do add a lot of clutter and diffing nonetheless.

Tapes can safely be ignored in PR reviews/diffs, FWIW. They're auto generated and there's nothing to review in them (aside from PRs that modified how they're saved, named, etc).

**Comment by zackkrida** [comment]
Ah, I can't believe I didn't even _consider_ SSR in this context. Thanks for that. I'll think about it a bit more, but probably best to keep things as-is.

**Comment by sarayourfriend** [comment]
Oh, we already manually re-write thumbnail URLs, we could just update the code that does that in `test/proxy.js::tapeDecorator` to replace them all with the same thumbnail. Then we could remove all but one thumbnail tape.

Problem with that though is that it would cause all thumbnails to have the same dimensions, which wouldn't exercise the image results page as expected.

**Comment by obulat** [comment]
I haven't thought about the thumbnail dimensions being important here :) I wonder if we could remove a lot of the thumbnail tape data (headers) and only leave the strictly necessary pieces. It might also help to move all the thumbnail tapes to a subdirectory that can be folded so that you don't see a long list of files there.

**Comment by sarayourfriend** [comment]
@zackkrida I think we can close this as "won't fix" right? Did you have any more ideas for how to address the original issue you were having while still preventing SSR from reaching out? Having differently sized thumbnails I think is important and using real thumbnail data for that seems to be the easiest.

Now that the new thumbnail proxy is live we could regenerate them and they might be smaller.

We could mark the tapes as binary in gitattributes or give them the generated attribute, whichever one forces them to not show up as needing review in PR diffs.

**Comment by zackkrida** [comment]
I'm comfortable closing this; my original concern was around size and I haven't seen these create large or significant diffs in quite some time.
