### ISSUE TITLE
Creator filter is unclear

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-frontend#1344]
## Description

It is unclear for users what the "Creator" checkbox in the filter pane accomplishes when searching.

## Screenshots
![image](https://user-images.githubusercontent.com/10214785/165648131-bde7bf4b-ee5b-4ce5-b2f5-997121e03151.png)

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
How should we fix this? Might it need a better label and/or a popup with more information?

**Comment by obulat** [comment]
The message of this filter is "Search by the creator, instead of searching by the title+description+tags". But of course, we don't say that we search by `title`+`description`+`tags` anywhere, so it becomes unclear. Should we make this section with a radio button, something like:

**Search by:**
- media data ? media title and description? - I don't know what the wording for the default search could be.
- creator

**Comment by sarayourfriend** [comment]
I wonder if we couldn't solve this by making it possible to search by creator _and_ the rest by making an `@` prefix denote creator names:

`@clevelandzoo birds` would search for "birds" anywhere where the creator matched "clevelandzoo".

Or really why differentiate at all between the creator field and the rest of them? Are result very different when we don't?

**Comment by cogdog** [comment]
This filter needs some kind of label or better indicator as to its purpose. As relatively new user of Openverse I had no idea what it did, especially hanging there alone after a list of ~50 sources, "Creator" just hangs out there.

Perhaps: "Limit Search To" or "Search within" with options:

* Title
* Description
* Tags
* Author

And for the reason is people who share media like to be able to track where their photos are. Or I may know of a creator and I want to find similar works. I have heard from people who would like the option search within all photos credited to a person for a keyword (like @sarayourfriend suggests with finding Cleveland Zoo's photos of birds).

At a minimum a label would help.

**Comment by sarayourfriend** [comment]
@cogdog I like your idea of addressing this, at least to start with, by improving the label. Perhaps "Search based on creator name" would be a good start (based roughly on your suggestion)? Additionally, it could be good to move this to the top of the filter list rather than at the very bottom (where it is surely lost, especially on mobile image search).

I do think there are larger questions about this that we could evaluate further, but potentially in a different issue with a broader scope. It'd be a shame to delay this improvement by trying to find the absolute perfect solution.

*Note*: I don't think "Limit search to" is appropriate because my understanding is that we do not currently include those fields... "limit to" implies that the default search includes them and we're just "narrowing" the scope with those options. I could be wrong in my understanding of how the search works though :slightly_smiling_face:

**Comment by cogdog** [comment]
I don't have the definitive label, just wanted to point out that as is, the filter is very unintuitive. 

I agree it should be moved above the long list of source filters (to be honest, I would suggest that maybe those are opened by some kind of accordion or HTML details /summary tags to show/hide.

But I can see now how Creator works as a filter. A search on `Dogtrax`

https://wordpress.org/openverse/search/image?q=dogtrax

yields a top image that includes this in the title created by mrkdavis, but the rest of them are photos created by a flickr user with this Dogtrax handle (I know him, a very creative teacher) which are revealed by applying the Creator filter

https://wordpress.org/openverse/search/image?q=dogtrax&searchBy=creator

**EXCEPT**... [the more general result](https://wordpress.org/openverse/search/image?q=dogtrax) (the first) yield 38 matches, while [filtering by creator for the second](https://wordpress.org/openverse/search/image?q=dogtrax&searchBy=creator), yields 3807 matches.

This is counter intuitive...how does filtering a search produce more results?

**Comment by sarayourfriend** [comment]
All the results on the first example, without the creator filter, include `dogtrax` in the title (and many are not from dogtrax himself). The second includes all of dogtrax's own works, which are impressive in number :slightly_smiling_face: 

It comes down to, as I said, that the search does not by default include the creator field and only searches things like title, tags, and description:

https://github.com/WordPress/openverse-api/blob/7d867cbc284f0f2759b387f96418de21bdef800b/api/catalog/api/controllers/search_controller.py#L338-L367

If you check the linked code, you'll see an if conditional that says: if we're doing a normal search (no "advanced" filters), then search all the fields in the `search_fields` list ("tags.name", "title", "description"). Note that this does not include the "creator" field. In the "else" branch of the conditional, we get the "advanced" search, which you'll notice that each of the "advanced" options are applied individually. The only one surfaced on the frontend is the creator field but you can see tags and title can also be "specifically" searched against.

I'm not sure of the exact reason or history of why creator is excluded from the `search_fields` list, but I suspect you probably get some really unuseful results if you do include it. For example, there's bound to be lots of users with the word "dog" in their handle that don't have any pictures of dogs, which is what you'd hope for if you searched for "dog".

In any case, if you'd like to open a PR to update the text of the label and move the checkbox to the top of the filter sidebar, I think that would be great. If you're not able to do that, I've added the "good first issue" label here, so hopefully it'll get picked up by someone soon :tada:

**Comment by cogdog** [comment]
Thanks for the explanation and I agree with your guesses in the reasoning here plus in practice I would guess there are not too many cases where people search by Creator. 

It does look like, if I guess at the code, there is a possibility of searching just tags, title, or description., so could all be filters like Creator.

I appreciate you taking time to comment here; I do not have the tech chops to submit a PR, I just like to use things and ask lots of questions.

**Comment by sarayourfriend** [comment]
Sounds good, thanks for contributing this way, @cogdog. It's a great help to clarify requirements and get this issue ready for someone else to work on :pray:

**Comment by obulat** [comment]
> If you check the linked code, you'll see an if conditional that says: if we're doing a normal search (no "advanced" filters), then search all the fields in the `search_fields` list ("tags.name", "title", "description"). Note that this does not include the "creator" field. In the "else" branch of the conditional, we get the "advanced" search, which you'll notice that each of the "advanced" options are applied individually. The only one surfaced on the frontend is the creator field but you can see tags and title can also be "specifically" searched against.

The way I understand the code you linked, @sarayourfriend, if we search using `creator` filter, we only search in the creator field. The else branch seem to be creating a completely new `s` search query that searches through a single field: `s = s.query("simple_query_string", query=creator, fields=["creator"])`.

I've added a `needs design` label and removed the `help wanted` and `good first issue` labels because we need a design decision before implementing this. @panchovm, what would be the best way of clarifying what this filter option does? Do you agree with moving the filter to the top?

**Comment by sarayourfriend** [comment]
> The way I understand the code you linked, @sarayourfriend, if we search using creator filter, we only search in the creator field. The else branch seem to be creating a completely new s search query that searches through a single field: s = s.query("simple_query_string", query=creator, fields=["creator"]).

This is my understanding as well. It is what I meant to convey in my summary of the code.

It's not a "completely new query" though as it builds off the existing `s` query. Sort of like how you can chain ORM QuerySet methods and assignments to build a QuerySet over multiple lines. This means the "advanced" filters can build on each other. If we exposed a "title" and "tags" checkbox on the frontend along with creator they could all three combine to search in those fields.

Might not be important details for this specific ticket though :thinking: But if we wanted to _use_ those additional two advanced filters maybe Francisco can keep that in mind during design if we'd want to accommodate them in the future or now?

**Comment by obulat** [comment]
@panchovm, maybe it would be better to just remove the "Creator" checkbox from the filters pane for now, until we implement a better search by creator UI?

**Comment by zackkrida** [comment]
@obulat the other alternative I've considered and discussed with @panchovm a bit is adding some type of headline above the creator checkbox, like this:

![CleanShot 2023-02-01 at 17 12 53](https://user-images.githubusercontent.com/6351754/216175512-edc3c700-cbb3-4def-ba4e-1987d7a6b711.png)

**Comment by panchovm** [comment]
For this case, and since we dropped many ideas for the [2023 goals](https://make.wordpress.org/openverse/2022/11/16/thinking-towards-2023/), I am drawn to follow Olga's suggestion and hide the filter until we design a better approach for this and other similar use cases.

**Comment by cogdog** [comment]
That seems reasonable, I would guess it's a filter barely used. For anyone who can manually edit URLs, it will still work, right?

https://wordpress.org/openverse/search/image/?q=cogdogblog&searchBy=creator

**Comment by obulat** [comment]
> That seems reasonable, I would guess it's a filter barely used. For anyone who can manually edit URLs, it will still work, right?
> 
> https://wordpress.org/openverse/search/image/?q=cogdogblog&searchBy=creator

That's a great point, @cogdog! We will not be removing the URL functionality, only the UI for it!
