### ISSUE TITLE
Attribution box does not show for some results when navigating to them from search results page

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#1656]
## Description

If you visit https://search-production.openverse.engineering/image/3d96348f-5b9f-4ce7-8854-8480fa3bf1a0 from the search results page (it's on the first page of "dog" + "cc0") the attribution box will not appear.

## Reproduction

1.  Visit https://search-production.openverse.engineering/search/?q=dog&license=cc0
2.  Find the result linked above (it's the second image result at the time of writing this issue) and click it
3.  See that there is no attribution box

## Screenshots

![image](https://user-images.githubusercontent.com/24264157/184342890-3929fd58-c5f2-4978-a2e0-cc867793c808.png)

## Environment

 - Device:  laptop
 - OS:  Linux saras-laptop 5.18.15-arch1-2 &#35;1 SMP PREEMPT_DYNAMIC Mon, 01 Aug 2022 18:58:16 +0000 x86_64 GNU/Linux
 - Browser:  Firefox
 - Version:  Mozilla Firefox 103.0.1

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
Another example: https://wordpress.org/openverse/image/28dae73a-0a61-4585-a25a-7389f4b0bf77, search for "music" + "cc0" and it's on the first page of image results.

**Comment by dhruvkb** [comment]
Here is the cause of the issue:

1. The API does not send the `license_url` field for some results (^the ones that present the above issue) in the [search results endpoint](https://api.openverse.engineering/v1/images/?q=dog&license=cc0).

![image](https://user-images.githubusercontent.com/16580576/185296305-4bf7c519-64ec-456f-b1c2-12b0e76fff8a.png)

2. `VMediaReuse` only shows the attribution box if the `license_url` is present. This is a redundant condition because we can generate the URL on the frontend.

<img width="646" alt="Screenshot 2022-08-18 at 10 22 00 AM" src="https://user-images.githubusercontent.com/16580576/185296578-4bcf42c8-6061-4547-83f9-5d1833f05b4f.png">
