### ISSUE TITLE
Filter sidebar should be a bit wider to accommodate scrollbar

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#2028]
## Description

The filter sidebar's width is incredibly tight. If the scrollbar is visible, the text in the sidebar breaks into multiple lines and that looks odd.

## Reproduction

1. Open single media-type search results. Eg: https://search.openverse.engineering/search/image?q=cat
2. Enable scrollbars in your OS settings.
3. See error.

## Screenshots

![image](https://user-images.githubusercontent.com/16580576/205728149-244c5909-46cf-4b9d-babe-587dc90b9282.png)

## Additional context

Increasing the sidebar width a little (~17px IIRC) should fix the problem. Alternatively we could update the design so that it adapts well to narrower spaces (like putting the license icon and text on separate lines from the start).

But I'll leave that up to @panchovm.

**Comment by panchovm** [comment]
Thanks for bringing this up. Great finding.

We can tackle the change here rather than making a new mockup. The improvement sounds quick.

I noticed that the sidebar's width is `316px`, and since you are suggesting adding ~17px, I wonder if we are using a `8x` value. If so, then we can set it as `336px` (42 * 8).

What do you think @dhruvkb?

**Comment by dhruvkb** [comment]
That should work 👍. I'll see if that change fixes the issue locally and open a PR if it does!

**Comment by obulat** [comment]
@dhruvkb, I believe this is the same issue as https://github.com/WordPress/openverse-frontend/issues/1412. Shall we close it, or link it in your PR?
