### ISSUE TITLE
Make e2e and visual regression Playwright tests run in parallel

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#2041]
## Problem

Currently, the Nuxt Playwright tests step of the CI workflow builds the Nuxt app and then runs the e2e tests, followed by the visual regression tests. This takes a long time, between 15 and 20 minutes.

## Description

We could split the Playwright tests into two parallel actions: e2e and visual regression. This would make them faster. However, if we simply split the two, we would need to build the Nuxt app twice. 

@WordPress/openverse-frontend, @sarayourfriend, is there a way to build the Nuxt app once and re-use it for both e2e and visual regression Playwright tests?

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
> is there a way to build the Nuxt app once and re-use it for both e2e and visual regression Playwright tests?

Yes, I think relatively easily: build Nuxt and then map the `.nuxt` directory from the host into the Playwright container where the build output would normally go. To share it between simultaneously running jobs, we can make the Playwright runs a dependent of the Nuxt build check and have the build check upload successful build's `.nuxt` directory as a build artifact.

We'd need to do something to stop the Playwright container from building in CI, so check for the same CI variable that we use elsewhere in the Playwright configuration to skip the in-container build process.

Doing this wouldn't save any time overall though, I don't think. It might use slightly less of our GitHub Runner allowance, but not by much. I don't think it would save time because we'd still need to wait for both to run after the build happens.

If whoever implements this decides to take an easy route, I would recommend just adding separate steps for the two separate runs of the playwright tests:

```
pnpm run test:playwright -- visual-regression
pnpm run test:playwright -- e2e
```

That is the easiest win for the particular issue identified here. Then potentially a subsequent issue could be opened to make improvements that lower overall resource usage and speed-up re-runs even more (by re-using the same build).

You may run into timing issues with Talkback starting though. There is a note about this in the configuration file for the playwright tests to take care when debugging with the same build via the "hack" I noted there: https://github.com/WordPress/openverse-frontend/blob/640c1f293f9f6a9f5fc1a1d54f2186d7c7b66ad4/test/playwright/playwright.config.ts#L16-L30
