### ISSUE TITLE
Audio keeps playing on a single image result

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#2118]
## Description

On desktop, audio keeps playing when the image result is clicked after playing an audio from the results page.

## Reproduction

1. Search for something on desktop in the All content view.
2. Play a longer audio.
3. Click on an image result.
4. Hear error: the audio keeps playing, and there is no UI control for the user to stop it.

## Additional context
First reported by @dhruvkb.

**Comment by dhruvkb** [comment]
I recommend downgrading the priority to 'low' or 'medium' because

- the scenario for occurrence is not plausible, a person looking for images is unlikely to play an audio track
- the stakes are very low, pressing Back takes the user to the search results where the pause button is available

**Comment by dhruvkb** [comment]
I think I've narrowed this issue down to this `if` condition.

https://github.com/WordPress/openverse-frontend/blob/184d88df95d545caba29abe60bea12594c81b5cf/src/components/VAudioTrack/VAudioTrack.vue#L299-L302

This condition always evaluates to `true` because of the second part. An audio played from the search results will continue to play (even when navigating to a different page) because it will be present in the media store.
