### ISSUE TITLE
[Bug] Information list looks strange with long names (German)

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#248]
## Description
In German, the information box for an individual result looks strange because of the large amount of horizontal space between some, but not all, of the items.

## Reproduction
Switch your language to German and go to an individual results page like `/photos/7992f788-c8f6-459c-8186-b87edfb6bebe`. Click the `Information` tab on the right hand side.

## Expectation
The Information box should be spaced in a visually pleasing way

## Screenshots

<img width="331" alt="Captura de Tela 2021-09-20 às 13 24 28" src="https://user-images.githubusercontent.com/24264157/134070407-4d572c06-3c68-425c-87a8-4dcced223c6d.png">

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

cc @panchovm

**Comment by panchovm** [comment]
I think we should implement an adaptive format that increases/decreases columns width depending on label lengths while having a `64px` spacing between columns, something [like this](https://d.pr/i/zlPWzM).

This issue is from the current interface rather than from the audio integration context. Right? Just making sure we are on the same ground.

**Comment by zackkrida** [comment]
> current interface

Yes @panchovm.

**Comment by zackkrida** [comment]
A fixed width and the following css should do the trick:

```css
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
```

**Comment by krysal** [comment]
Closing as this was fixed with the redesign of the details page.
