### ISSUE TITLE
[Bug] Audio track styling on narrow displays

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#273]
The audio tracks don't look great on small screen sizes. @panchovm is currently making mockups for small devices, so this PR will likely be ready to work on soon.

**Comment by panchovm** [comment]
I've been working on this view, and here is a video showing the audio interaction.

https://user-images.githubusercontent.com/895819/141809401-9631c84c-8954-4f2b-a870-001f9da904f0.mov

Some comments about the changes and interactions:
1. The main audio component is based on the **full size** version with minor tweaks as timestamp spacings and the focus style area.
2. When you play the audio and scroll down to reach an area where the full-size component is no longer visible, the audio player appears from the bottom.
3. The audio player is necessary since you can also play any of the related audio suggested.
4. Close action in the audio player stops and closes the player.
5. Pausing the audio does not close the audio player.
6. Changing the audio format opens a popover menu, similar to its desktop version. Image below.

<img src="https://user-images.githubusercontent.com/895819/141810593-1f6f3a56-e078-4408-b8d8-49819b5f2d87.png" width="400">

My main concern with the audio player is that it does not allow the time-seeking navigational states. I was thinking of an interaction similar to SoundCloud, where you can navigate the time on a full-screen mode.

https://user-images.githubusercontent.com/895819/141812003-e2470807-d2b8-4a2d-aa1d-0e623e2318dc.MOV

I would like to hear your thoughts.

**Comment by sarayourfriend** [comment]
I love the global shared audio player pinned to the bottom of the screen on mobile. I also really appreciate that the design is a mobile version of the desktop. That should make it a lot easier to adapt the existing desktop screen to mobile.

If you're playing a related audio and then scroll back up to the top of the result page, what would it look like then? Would you have the result player shown _and_ the global player pinned to the bottom playing the related audio? Would the global player disappear if you were still playing the original result audio? If you're playing a related audio and then tap play on the result audio, would the global player disappear?

Also, if you start playing the result audio and then halfway through start playing a related audio, would your timestamp be saved on the result audio if you scrolled back up and started playing it again? Or would it start over? Do we need to save timestamps for every result so that if you play any related audio, switch to another and then back again, it'll pick up where it left off?

**Comment by panchovm** [comment]
Let me point all the cases I was considering. This idea is fully open to discussion, I might be missing some use cases but this interaction makes sense to me.

Before diving into it, we need to consider the following:
1. Result audio is always visible on the top of the page in a state that depends on user action.
2. Global player is always bottom-fixed and appears when result audio is no longer visible on the screen.
3. Related audio is always visible in the related audio section in a state that depends on user action.

## Playing the result audio
When opening the single result page, the result audio is in its `resting` state. When playing the result audio, the result audio changes to `playing` state.

 When scrolling down until the result audio is no longer visible, the global player appears bottom-fixed playing the result audio.

![image](https://user-images.githubusercontent.com/895819/141831085-709b2a6b-c4db-4a10-a6ea-285f49484a42.png)

## Switching to play a related audio
When playing a related audio by clicking on the audio cover, the global player starts playing the related audio, the related audio changes to `playing` state, and the result audio changes to its `resting` state without saving any timestamp.

![image](https://user-images.githubusercontent.com/895819/141831102-392b34c6-6ee9-4582-a662-947d869ad1ee.png)

## Switching back to play the result audio from playing a related audio
When you play the result audio while playing the related audio, the result audio changes to `playing` sate, the global player plays the result audio, and the related audio changes back to `resting` state.

![image](https://user-images.githubusercontent.com/895819/141831085-709b2a6b-c4db-4a10-a6ea-285f49484a42.png)

## Closing the global player
If you are playing either the result audio or the related audio, closing the global player stops the audio without saving any timestamp. Playing the result or the related audio, it starts from zero.

**Comment by panchovm** [comment]
I updated the [audio component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=314%3A7382) by adding this new mobile version called **Full size M**. I also added the [Focus style version](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=1033%3A3128) and all [the states](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=314%3A7372) related to its interaction.

## Reference
<img src="https://user-images.githubusercontent.com/895819/143492503-eafdc260-7cf7-4062-9e61-67f3ca7816c5.png" width="300">

**Comment by dhruvkb** [comment]
The 'Full S' layout has been implemented in #504.
