### ISSUE TITLE
Use Tailwind default screen breakpoints and/or add one for smaller screens

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse-frontend#391]
## Description

Currently our configuration for screens sizes in Tailwind looks like this:

```js
screens: {
  // Determined by the lower bound of screen width
  tab: '768px',
  desk: '1024px',
  wide: '1216px',
  hd: '1408px',
},
```
It uses ambiguous custom names, since `desk` could span all screens that are larger than `tab` and `wide` and `hd` feels unintuitive.

We should consider renaming those to more generic and standard names as [Tailwind defaults](https://tailwindcss.com/docs/breakpoints) (`md`, `lg`, `xl` ...), and include a breakpoint for smaller devices; frequent options are `480px` and `640px`.

## Alternatives

Make changes specific to smaller screens manual with media queries on each page. I don't think we really want to go this path.

## Additional context

The mockups for [mobile designs in Figma](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=133%3A11555) have a width of **375px**. 
@panchovm can also help by sharing what he uses here. 

## Implementation

- [x] 🙋 I would be interested in implementing this feature once we agree on using the default tailwind names or new ones :)

**Comment by panchovm** [comment]
I have been using `375px` on mobile mockups to preview them on my phone (iPhone 12 Pro), but I fully agree with following Tailwind definitions. I have always considered Apple iPhone 3GS as the smallest size (`320px`), but it seems outdated in terms of use.

My understanding is that breakpoints are set for interface changes. In this case, the elements that change significantly are the header, filter area, and audio component. I don't have any preference since those can use the mobile version until reaching the `md` breakpoint.
