### ISSUE TITLE
Make Header RTL-compatible

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#426]
Action items:
- The navigation items should be aligned with the left side of the screen
- The dropdown items should not have a large leading gap
- Should the openverse logo be on the opposite side of the openverse brand text? cc @panchovm

**Comment by dhruvkb** [comment]
As for question 3, I'm fairly certain the icon will be to the left of the text [^apple] [^spotify] [^wordpress].

[^apple]: <img width="498" alt="Screenshot 2021-11-18 at 9 31 50 AM" src="https://user-images.githubusercontent.com/16580576/142357620-86f99934-5e61-42d4-b0c7-84dfa9a39940.png"><br/>

[^spotify]: <img width="1233" alt="Screenshot 2021-11-18 at 9 32 21 AM" src="https://user-images.githubusercontent.com/16580576/142357675-5efe7d8d-c81f-436c-bc78-79fcdeaa1dee.png"><br/>

[^wordpress]: <img width="1210" alt="Screenshot 2021-11-18 at 9 32 09 AM" src="https://user-images.githubusercontent.com/16580576/142357662-c194dc53-902d-459b-8216-a4a58dd141ad.png"><br/>

**Comment by dhruvkb** [comment]
Fun thing is that no-one translates the wordmarks either. How is a non-english speaker supposed to read them?

**Comment by panchovm** [comment]
I would love to see the openverse logo translated into other alphabets.

For now, the logo is an SVG file with the **openverse** word in it, so having it in LTR as the examples above sounds reasonable. But since we're using Inter as brand font, we can have the symbol separated and apply an RTL logic where text is on the left and logo on the right.
 
That gives me a reason to keep boosting the use of the symbol as a universally readable element.

**Comment by zackkrida** [comment]
A lot of the reason for _not_ translatiog logo/wordmarks is related to copyright.

**Comment by dhruvkb** [comment]
What's also interesting is how the meaningfulness of the brand name works. When i18n-ifying
- **Apple Music**: we'd transliterate "Apple" and translate "Music". No meaning lost.
- **Spotify**: we'd transliterate it and since the original word had no meaning, none is lost.
- **Openverse**: we'd transliterate it and the meaning of "open" and "verse" in English would be gone.
