### ISSUE TITLE
Add smaller size for Download button

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-frontend#510]
## Problem

The 'Full size S' layout for the Audio track users a smaller download button (40px height) as compared to the one used in 'Full size M' (53px height).

The Download button currently does not offer this size.

## Description

The `DownloadButton` component, which inherits from the `DropdownButton` component should provide two size configurations to choose from, the existing bigger size and the new smaller size.

## Additional context

Figma node: https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=1029%3A5890

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
Would be nice to re-implement the DownloadButton component using the VButton component as part of this ticket. Then the size issue would automatically be handled.

This is contingent on being able to override the button's default corner rounding behavior. Might need to make a small refactor to the button to lift the "base" styles out of the `<style>` sheet and directly into the classes applied to the button so that it doesn't take precedence over parent-applied classes.
