### ISSUE TITLE
Add license definition in filter sidebar

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#541]
## Problem
The current mockups do not have the license definition in the Licenses section, and we need to show a license explanation and a link to the license description per license.

## Alternatives
This proposal adds a right-aligned help icon showing the license definition in a box. The interaction goes as it follows:
1. On hover, the `help` icon turns `dark-charcoal` and a tooltip appears on its left.
2. On click, the license explanation box appears top-aligned to the license checkbox.
3. Clicking outside the license explanation box closes the box.
4. Clicking on a different `help` icon closes the current box and opens the new one.

Here is a video showing the interaction. As noticed below, the checkbox state (enabled, disabled) does not affect the license explanation interaction.

https://user-images.githubusercontent.com/895819/146779058-a98903b0-5ed6-496d-9c36-bcdb9415bb0c.mp4

## Additional context
The popover design has a **shadow popover** style from the [WordPress Design Library](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library).

**Comment by sarayourfriend** [comment]
This looks good to me, but my initial gut reaction is that the popup feels "far away" from the question mark circle icon that triggers it opening. Gutenberg has similar interactions that open popovers to the side, but the triggers for them all seem to be wider, so the popover is more likely within the immediate vision of a user.

https://user-images.githubusercontent.com/24264157/146839961-8b528490-0b77-4d1b-b6bf-acd3d14a60b7.mov

The biggest thing that helps with this for sighted users is probably the animation visible in the video above. I wonder if we could do a similar thing?

Also a note for implementers: our popover doesn't currently support arbitrary placement like this. I think it could be done by making the popover relative to the checkbox as a whole group, but it would require a new prop to explicitly pass the "anchor" element for the popover to use. Right now it just uses the disclosure/trigger element, which in this case would just be the circle question mark icon.

We'll also need to add a prop for configuring the gutter size to displace the popover far enough away from the checkbox "row" so that it appears over the search results.

@panchovm for mobile, will this also open a modal?

**Comment by panchovm** [comment]
It's worth trying the popover animation to see how related it feels to the action. I tried placing it above and below as usual, but the outcome does not look good and covers other filters.

<img width="400" alt="CleanShot 2021-12-21 at 09 34 04@2x" src="https://user-images.githubusercontent.com/895819/146930769-243a0502-2128-48d1-bf7d-94d97fe7410f.png">

## Popovers on mobile

Regarding popovers in general, I was thinking of that while designing this, and it seems reasonable to find a single solution for all popovers on mobile.

The audio format selection and the report content have similar interactions (as shown in #543). And for the safe browsing filter (shown in #542), moving it to the filter modal in a new category/section seems good as it belongs to the same concept of reducing results, and it does not split the search result layout.

<img width="300" alt="CleanShot 2021-12-21 at 09 41 41@2x" src="https://user-images.githubusercontent.com/895819/146931729-16bcb084-01db-43d1-88da-43eb0c8cfa21.png">

**Comment by panchovm** [comment]
I am still iterating on this and I think that placing the popover above and right-aligned to the question symbols solves the popover interaction on desktop and mobile. Here is a prototype for the two breakpoints.

The component has the same content and interactions on both breakpoints. The mobile version also applies to the reporting content flow (#543) and it might work well for the format selection in audio.

### Desktop
https://user-images.githubusercontent.com/895819/147097662-09e3b0a5-5157-440d-b9da-9d65fd529de7.mp4

### Mobile
https://user-images.githubusercontent.com/895819/147097690-815f4c3e-2af7-4ff7-9711-a58696c77dde.mov

**Comment by sarayourfriend** [comment]
Love it! From a technical perspective it'll still be a popover on desktop and a modal on mobile, but I think that's totally doable.

**Comment by panchovm** [comment]
Perfect. I will update the Releases and Design Library files.
