### ISSUE TITLE
Audio result page responsiveness is messy

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#544]
## Description

The audio result page's responsiveness is kind of messy at the moment.

## Reproduction

1. Go to an audio result page
2. Resize the browser window from large to small screen size
3. Notice several elements on the page moving at different intervals and some based on different text widths.

## Expectation

We should be more proactive/defensive against window resizing and rearrange elements all at once instead of some elements at the medium breakpoint and others at the small breakpoint. Of particular concern is the wrapping on the play/pause button, track info, and download button. Either we need to reserve that layout for only large or xlarge screens or we'll need to rethink how it works at smaller sizes.

Additionally, long titles for tracks will cause wrapping issues as well:
<img width="1337" alt="Captura de Tela 2021-12-20 às 14 28 48" src="https://user-images.githubusercontent.com/24264157/146841154-fa085e61-71a1-4233-b607-f4f8465b21de.png">

Long artist names will also cause wrapping issues, but different ones!
<img width="1337" alt="Captura de Tela 2021-12-20 às 14 29 25" src="https://user-images.githubusercontent.com/24264157/146841206-15c8dcba-97c6-45d8-af7d-9cb66c0dedb2.png">

## Screenshots

Here's a video showing the current state of responsiveness of the screen:

https://user-images.githubusercontent.com/24264157/146840902-f127251e-59d5-4355-b75b-75a6d88f3b80.mov

## Environment

 - Device: 
 - OS: 
 - Browser: 
 - Version: 
 - Other info: 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

cc @panchovm, we'll need your help thinking about how to handle some of these cases. I was digging around the Audio Integration figma and I noticed some places (for the row version) we truncate these informations. That seems less than ideal for the full result page though. Maybe we can take advantage of the extra space and break things up into separate isolated rows?

**Comment by panchovm** [comment]
## Modal containers
All modal breakpoints have a container for the content, except the audio wave. I was exploring different solutions as it expands to reach the modal width and the page view, take a look at the #480 when you can.

The logic I have been following is: On search results, truncate information is ok. On single result view, never truncate information. Here are the three layout variations for the modals. Notice that **Modal M** also applies to breakpoint `lg`, and **Modal L** to `2xl`.

<img width="1513" alt="CleanShot 2021-12-21 at 11 24 21@2x" src="https://user-images.githubusercontent.com/895819/146945685-fcfb552d-f778-45d7-a03b-93a67da21008.png">

## Audio component section
The first part, the audio component, is placed with the following spacings.

### Modal L (`xl`, `2xl`)
<img width="1091" alt="CleanShot 2021-12-21 at 11 26 22@2x" src="https://user-images.githubusercontent.com/895819/146946007-c81622c4-d2ab-4238-b8a5-3ef973a11a52.png">

### Modal M (`md`, `lg`)

<img width="500" alt="CleanShot 2021-12-21 at 11 33 35@2x" src="https://user-images.githubusercontent.com/895819/146947031-fa5e1a8f-62ad-4c29-9da8-0dc3ca062084.png">

### Modal S (`sm`)

<img width="500" alt="CleanShot 2021-12-21 at 11 33 56@2x" src="https://user-images.githubusercontent.com/895819/146947072-08b3f71c-57ed-4df1-bf6d-7ca5fb024ac6.png">

## Reuse content section
The reuse content section is divided into two `4-cols`, **License** on the left and **Credit the creator** on the right. Although I am not fully sure of the same logic for the **Modal S** (`sm`). It seems that we need another breakpoint for smaller sizes than `sm` definition, otherwise, both `4-cols` become full-width and it looks odd. Especially the **Credit the creator** box.

<img width="1668" alt="CleanShot 2021-12-21 at 11 45 16@2x" src="https://user-images.githubusercontent.com/895819/146948794-5af76d88-c036-4493-9aa4-542808480584.png">

**Modal S** idea: on the left, the full-width cols; on the right, two `4-cols`.

<img width="958" alt="CleanShot 2021-12-21 at 11 47 25@2x" src="https://user-images.githubusercontent.com/895819/146949163-ffc31563-53c1-4950-928a-37d279dea02e.png">
