### ISSUE TITLE
Redirect /search/ page to the Openverse homepage

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-frontend#596]
## Problem

Currently, when you go to `https://wordpress.org/openverse/search/`, you see an image page that confusingly states that you got no results for " ", and a `Load more` button. The page is not linked from anywhere, so you can only get there if you type in the exact address. 

<img width="934" alt="Screen Shot 2022-01-12 at 6 43 32 PM" src="https://user-images.githubusercontent.com/15233243/149173549-f43ee2ab-3eb0-45cf-bb3a-1f03e86a2cc4.png">

## Description

It is better for user experience to redirect this page to the home page (`https://wordpress.org/openverse/`), so that even if the user gets to the `/search/` address, they are not confused with incorrect text and impossible actions.

## Alternatives

We could design a special page for this address, but considering that it is not linked from anywhere, it doesn't seem to be a good use of time and resources.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
Keep in mind that this will be the endpoint of the 'all' results view in the redesign. And also that we use this endpoint for the links on the 'sources' page, for example 'Animal Diversity' links to https://wordpress.org/openverse/search?source=animaldiversity

Perhaps when this endpoint is hit without any filters or a search term applied, we should redirect to the homepage.

**Comment by kb-0311** [comment]
One possible solution I was thinking about is -  because the address needs to be typed and it is not linked to anywhere, because the openverse search page here, does not accept null query

https://wordpress.org/openverse/
![Screenshot (8671)](https://user-images.githubusercontent.com/96020697/156884451-db5cfb98-7330-4acc-b22c-20e654c3d9d0.png)

However. if you search for null query from the search bar instead of the address, here after searching for a non-null value first the page redirects to the previously filled non-null query value

https://wordpress.org/openverse/search/?q=aRandomTestToDemonstrateNullValues

Directly input a null value in the query from the address manually and you will see the same error

https://wordpress.org/openverse/search/?q=

So I guess the issue might be here - `opensorce-frontend/src/store/search.js` here the null value is not defined-

**Comment by kb-0311** [comment]
I am not sure . how would we redirect the search route with null query to the home page though? if that is the solution you want to implement.

As in I am unable to find the files where this URL change can be made

**Comment by sarayourfriend** [comment]
@kb-0311 I think you'd need to use the `redirect` function present on the nuxt context passed to `asyncData` to redirect to the homepage when `/search/` is reached with no query params: https://nuxtjs.org/docs/concepts/context-helpers#redirecting-users--accessing-the-store
