### ISSUE TITLE
Some images are showing trademark

### ISSUE THREAD

**Issue by sebastienserre** [WordPress/openverse-frontend#690]
## Description
In France, BHV is a big shop name and is trademarked: https://wordpress.org/openverse/photos/808f6e30-7255-424c-b07f-609625a97677
BHV is https://www.bhv.fr/ / https://fr.wikipedia.org/wiki/Bazar_de_l%27H%C3%B4tel_de_Ville

I don't think we should show them.

**Comment by dhruvkb** [comment]
@sebastienserre for copyright infringement, you should fill out the DMCA takedown form [here](https://docs.google.com/forms/d/e/1FAIpQLSd0I8GsEbGQLdaX4K_F6V2NbHZqN137WMZgnptUpzwd-kbDKA/viewform). We will review and remove images that are reported to us via this form.

The link to the form is also shown when reporting content using the "🚩 report this content" button below the image.
![image](https://user-images.githubusercontent.com/16580576/150694684-fee38ea0-ddf7-4182-a6ab-a452798adb75.png)

Since it's not a code issue, I'll be closing it with the 'invalid' label.
