### ISSUE TITLE
Update the meta search section with the new design

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse-frontend#734]
## Problem
The current external sources area in search results does not follow the redesign.
**_Updated issue:_** only the mobile popup needs to be implemented for this issue.

<img width="800" alt="CleanShot 2022-01-27 at 11 59 18@2x" src="https://user-images.githubusercontent.com/895819/151384406-b4d3dffa-74f6-4b62-a0c1-d507c7f5ace1.png">

## Description
We need to update the section with the design made on [the mockups](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=133%3A6869).

### ~~Desktop version~~ Done
<img width="1387" alt="Meta search on desktop" src="https://user-images.githubusercontent.com/895819/151384759-80cc75d9-a131-45f8-b1d0-be6c2d098f81.png">

### Mobile version
Instead of the current implementation in the popover, the external sources should open in a modal:
<img width="300" alt="Meta search on mobile" src="https://user-images.githubusercontent.com/895819/151384963-7252b7c4-5ef1-4dcd-8bd8-ef9062a8ac9c.png">

**Comment by dhruvkb** [comment]
Currently we have two ways in which the meta-search feature is reached.

- a search has zero results

<img width="610" alt="Screenshot 2022-06-28 at 11 35 35 AM" src="https://user-images.githubusercontent.com/16580576/176120958-56cd2e1e-3d75-45a8-b5d2-82e62e25a7b5.png">

- below the load more button of the search results

<img width="585" alt="Screenshot 2022-06-28 at 11 37 50 AM" src="https://user-images.githubusercontent.com/16580576/176121403-2bb70d2c-c65b-4fe3-b70d-9d4decb0bcc7.png">

@panchovm does this redesign only affect the second appearance?

**Comment by panchovm** [comment]
Yes @dhruvkb, only the second appearance. Although I would pause this work until we have a decision regarding keeping using the term "Additional."

**Comment by dhruvkb** [comment]
Good call @panchovm. I'll triage this issue as blocked for now.

**Comment by obulat** [comment]
@panchovm, we have already decided on renaming the feature to "External sources". Can we update the status of this issue?

Currently, meta search section uses a popover on all layouts: desktop and mobile, the bottom of the search results and the page shown when nothing could be found:
### Desktop
<img width="404" alt="Screenshot 2022-11-20 at 7 11 45 AM" src="https://user-images.githubusercontent.com/15233243/202885123-bc7bba3c-c2f2-4390-9604-71ac01d7f297.png">

### Mobile
<img width="507" alt="Screenshot 2022-11-20 at 7 12 21 AM" src="https://user-images.githubusercontent.com/15233243/202885128-d8493a52-0faf-4166-a5f8-fad77d79cf85.png">

### "Nothing found" page
<img width="495" alt="Screenshot 2022-11-20 at 7 12 57 AM" src="https://user-images.githubusercontent.com/15233243/202885131-fb0608e7-5f5d-4d33-b252-60eaed18dd9e.png">

From the comments on this issue, I understand we should do the following:

1. Use a modal for the mobile source selector instead of a Popover.
2. Use a button row for the list of external sources on the "Nothing found" page.

Is this correct, is there anything we need to add?

**Comment by panchovm** [comment]
You are right @obulat, the term no longer blocks the ticket.

Although this issue only covers point 1 in the way you describe it. For point 2, I think we do not have the ticket requesting the update or the mockup.
