### ISSUE TITLE
Switch to Pinia

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-frontend#756]
## Problem

Currently we use Vuex for global state management. This works fine for Vue 2 but has some considerable disadvantages for Vue 3, especially when it comes to TypeScript support and composition-api usage.

## Description

We should switch to Pinia instead. It is the new official default recommendation of the Vue project for state management instead of Vuex: https://blog.vuejs.org/posts/vue-3-as-the-new-default.html

It also has better interoperability between Vue 2's composition-api and Vue 3, and would allow us to decouple our state-management API usage from Nuxt. Currently we rely on Nuxt's home-grown `useStore` composable from the `@nuxtjs/composition-api` extension on top of `@vue/composition-api` but there's no guarantee that that composable will stick around in Nuxt 3.

[`useStore` will not exist in Nuxt 3](https://v3.nuxtjs.org/getting-started/bridge-composition-api#usestore) and we'll need to remove usages of it in order to be able to use Nuxt bridge anyway.

Nuxt 3 also includes a new composable called [`useState` that acts as an SSR friendly verison of `ref`](https://v3.nuxtjs.org/docs/usage/state#state). There are probably several things that we could transition to use that instead of Pinia... but it would take a lot more care to design sensible, reactive APIs around it.

## Alternatives

We could just stick with the current Vuex approach and during the Nuxt bridge upgrade replace all usages of `useStore` with `useNuxtApp().$store` instead. This would introduce more code changes during the Nuxt bridge upgrade BUT would prevent us from having to re-write our entire state management strategy before migrating to Nuxt 3. Curious what folks think about this so cc @WordPress/openverse-frontend for input on which direction to go in.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

Marking this as `high` priority because whatever decision we make here informs how the Nuxt bridge upgrade will be approached. If we choose to go with Pinia, then the Nuxt bridge upgrade would probably be stalled until we switched to it. Otherwise, the Nuxt bridge upgrade could be attempted again sooner.

**Comment by sarayourfriend** [comment]
I think the output of this issue should be a milestone with discrete tasks for converting specific stores to Pinia. The first issue of course would be to add Pinia to the frontend infrastructure and convert the smallest store possible to Pinia as a proof of concept.

We will also need to make sure to implement the correct SSR tooling for Pinia including client-side state hydration.

**Comment by obulat** [comment]
I agree with moving to Pinia before upgrading to Nuxt bridge, and created a milestone for it: https://github.com/WordPress/openverse-frontend/milestone/5
Since the stores are very interdependent, this conversion will probably work only after all of the separate issues are merged together. Because of this, we should probably create a feature branch to add all Pinia related PRs into.

The issues that need to be created:
- Refactor current stores to ensure that there are no getters and state properties with the same name (as in `media.js` store)

- Set up Pinia stores:
  - Run `pnpm install pinia @pinia/nuxt @pinia/testing`
  - Add `@pinia/nuxt` to the `buildModules` in `nuxt.config.js`
  - Add an `mjs` rule snippet[^1] to `nuxt.config.js`'s `build.extend` to ensure `mjs` files are treated correctly (and prevent errors like: `Can't import the named export 'watch' from non EcmaScript module (only default export is available)`)
  - Create `stores` folder and add `types.d.ts` from `store` folder into it.
- Convert each individual Vuex store to Pinia: store, tests, usage in components.
  
[^1]:`config.module.rules.push({test: /\.mjs$/, include: /node_modules/, type: 'javascript/auto',})`

**Comment by obulat** [comment]
Closing this issue because the switch is described in [Pinia conversion RFC](https://github.com/WordPress/openverse/blob/46df133abf9127c55ea5a3a98e766f1b2dd27dd1/rfcs/20220223-convert_the_store_from_vuex_to_pinia.md)

**Comment by dhruvkb** [comment]
For a second I thought the Pinia migration was complete!
