### ISSUE TITLE
Unable to choose images on landing page, under content types on the search bar

### ISSUE THREAD

**Issue by Ad-Mk** [WordPress/openverse-frontend#801]
## Description
While selecting between all content, images, and audio. The selector does not highlight images, when hovered over it. 

## Reproduction
Please refer to the screen recording
[Screen capture](https://drive.google.com/file/d/1V14ApXypuihar8FZg37zW79ln4AajHwL/view?usp=sharing)

## Expectation
The image option should be highlighted, when the cursor hovers right over it. 

## Screenshots
[Screen Capture](https://drive.google.com/file/d/1V14ApXypuihar8FZg37zW79ln4AajHwL/view?usp=sharing) - attaching for your reference

## Environment

 - Device: Laptops, Desktops 
 - OS: Windows 10
 - Browser: Safari, Firefox

**Comment by aniash29-cr** [comment]
Tried to dig into this. Found out that the issue is related to `z-index` for `<a>` tag for the site logo.

On a screen resolution greater than 1024px when the logo and images element are stacked side by side - opening the content-type dropdown puts it over the logo.

Trying to hover over the Images button in the popover menu does not allow you to select and click it effectively due to he z-index value of the site logo anchor tag.

Please check the attached screenshot for reference:

![openverse-popover-zindex](https://user-images.githubusercontent.com/48274650/152520204-ff13d07b-1622-4d0b-9dc8-c9dcbd33fb32.png)

**Comment by Ad-Mk** [comment]
> Tried to dig into this. Found out that the issue is related to `z-index` for `<a>` tag for the site logo.
> 
> On a screen resolution greater than 1024px when the logo and images element are stacked side by side - opening the content-type dropdown puts it over the logo.
> 
> Trying to hover over the Images button in the popover menu does not allow you to select and click it effectively due to the z-index value of the site logo anchor tag.
> 
> Please check the attached screenshot for reference:
> 
> ![openverse-popover-zindex](https://user-images.githubusercontent.com/48274650/152520204-ff13d07b-1622-4d0b-9dc8-c9dcbd33fb32.png)

**Comment by zackkrida** [comment]
Here's an additional screenshot that makes the z-index issue quite obvious:

<img width="492" alt="CleanShot 2022-02-04 at 08 39 09@2x" src="https://user-images.githubusercontent.com/6351754/152538407-ec8dd9d9-68fc-4363-be72-2d7fc09f400b.png">

**Comment by obulat** [comment]
This issue can be solved by removing `z-10` class here:
https://github.com/WordPress/openverse-frontend/blob/23b686270a5c131b7feb69dc6df683c221d81ce7/src/pages/index.vue#L18
Is there a reason to set the `z-index` on the `NuxtLink` here?
