### ISSUE TITLE
About page is broken

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-frontend#825]
## Description
	
![CleanShot 2022-02-07 at 21 48 41@2x](https://user-images.githubusercontent.com/6351754/152908673-07a837b7-cab6-450b-908e-f53640e83ccb.png)

Due to what looks like a mysterious empty `div` floating in the page, the css grid styles for the primary Openverse page layout are broken on the about page.

- https://search-staging.openverse.engineering/about

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
Seems to be the header specifically, it happens when the page is not full filled with content.
See https://search-staging.openverse.engineering/search/image

<kbd><img width="1434" alt="Search Image results page empty, the header extends to fill half the page." style="border: 1px solid black;" src="https://user-images.githubusercontent.com/9145885/153052163-fa8ec58f-aa65-40a2-8e8c-28d5f1914cbe.png"></kbd>
